######################################################################
# Automatically generated by qmake (2.01a) Sat Dec 20 15:55:10 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
win32:LIBS += -LC:\libs -lWS2_32


# Input
HEADERS += mainwindow.h ansitohtml.h qinputedit.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp ansitohtml.cpp qinputedit.cpp
QT += network
